### ISSUE TITLE
Change event not firing

### ISSUE THREAD

**Issue by matt-landers** [arschmitz/jquery-mobile-datepicker-wrapper#12]
When selecting a date, the change event is not firing.  This makes it difficult to use with data binding libraries.  Is there a workaround or fix for this?

**Comment by indrimuska** [comment]
You have to bind the onSelect event of the datepicker.
Unfortunately it's not supported at the moment, that's why I decided to implement it as I describe in my merge request #8 (see on commit **Bug fix: custom callbacks allowed**).
This is my version of [jQm datepicker wrapper](https://github.com/indrimuska/jquery-mobile-datepicker-wrapper).

**Comment by matt-landers** [comment]
I just hacked the ui.datepicker to fake a keyup event which solves the problem nicely.

**Comment by albertoiglesias** [comment]
an example of on select event?

please
