### ISSUE TITLE
onSelect

### ISSUE THREAD

**Issue by 1lexis** [arschmitz/jquery-mobile-datepicker-wrapper#19]
Hi,

I don't understand how to use onSelect property with jqm datepicker wrapper.

Can you help me please ?

Regards.

**Comment by indrimuska** [comment]
Current version of the datepicker-wrapper doesn't allow the use of onSelect / onChangeMonthYear / beforeShow callbacks, because they're used to set the style of the calendar. If you override them, you have to set the style manually.

If you want you can take a look to my proposal at #18 (demo [here](http://jsbin.com/indrimuska/42/edit)).

**Comment by arschmitz** [comment]
@1lexis @indrimuska is correct currently there is a bug in this regard hope to get this fixed very soon @indrimuska sorry its taken me a bit to get to these been really busy hope to very soon.

**Comment by indrimuska** [comment]
:ok_hand:  No problem, take your time!
